name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "This job is now running on a ${{ runner.os }} server host by GitHub!"
    - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}"
    - name: Check out repository code
      uses:  actions/checkout@v4
    - run:  echo "The ${{ github.repository }} GitHub repository has been cloned to the runner"
    - run: echo "The workflow now is ready to test your code on the runner"
    - name: List files in the repositories
      run: |
        ls ${{ github.workspace }}
    - run: echo "This job status is ${{ job.status}}"
